### ISSUE TITLE
specest_gui.py error

### ISSUE THREAD

**Issue by stoughto** [kit-cel/gr-specest#16]
Cloned and installed on Ubuntu.  Compile, test, and install with no complaints.

specest_gui.py opens gui but does not respond to "run" button.  Here is what is in the window where it started:

$ specest_gui.py
linux; GNU C++ version 5.3.1 20160413; Boost_105800; UHD_003.010.git-216-gb1c2d4bb

/usr/local/share/gr-specest/4cos.dat: No such file or directory
Could not initialize file-source!
Could not initialize UHD source!
Could not initialize UHD source!
Could not initialize UHD source!
Could not initialize UHD source!
Could not initialize UHD source!
Traceback (most recent call last):
  File "/usr/local/bin/specest_gui.py", line 594, in run_flow_graph
    self.fg.start()
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/gr/top_block.py", line 109, in start
    top_block_start_unlocked(self._impl, max_noutput_items)
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/gr/runtime_swig.py", line 5678, in top_block_start_unlocked
    return _runtime_swig.top_block_start_unlocked(r, max_noutput_items)
RuntimeError: resolve_port: hierarchical block 'head': output 0 is not connected internally
stoughto@stoughto-VirtualBox:~$

**Comment by Chzn4Lifez** [comment]
It's clearly a problem with your USRP, if you have one.
