### ISSUE TITLE
grc: Uncomment options section which didn't work on old GNU Radio releases

### ISSUE THREAD

**Issue by noc0lour** [kit-cel/gr-specest#21]
On newer GNU Radio releases the option key for parameters actually works. So window selection can be actually done. Maybe even having a custom window field so users can supply their own window taps.

E.g. welch specest block:
https://github.com/kit-cel/gr-specest/blob/748aa13b97ed6ea1a747e6451cd5c8f1aaace7a2/grc/specest_welch.xml#L40

**Comment by mbr0wn** [comment]
This is actually fixed on newer gr-specest versions.
