### ISSUE TITLE
Not able to install gr-specest on ubuntu 16.04

### ISSUE THREAD

**Issue by pachpandepriti** [kit-cel/gr-specest#23]
he Fortran compiler identification is unknown
CMake Error at CMakeLists.txt:26 (enable_language):
  No CMAKE_Fortran_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!

**Comment by fwunsch** [comment]
It seems you don't have a Fortran compiler installed.

**Comment by pachpandepriti** [comment]
Can you please guide me with correct steps to install the gr recipe files for gnuradio.I also need to install gr-mediatools. It's giving the same error while installation.

Thanks in advance

**Comment by pachpandepriti** [comment]
I installed everything as mentioned in the readme file

**Comment by marcusmueller** [comment]
And did you follow the instructions in the error message?

**Comment by mbr0wn** [comment]
No more activity, closing.
