### ISSUE TITLE
GRC YAML: 'part' if vlen == 1

### ISSUE THREAD

**Issue by sodaBitters** [kit-cel/gr-specest#26]
in all gr-specest GRC blocks, this YAML line is present on the FFT Length parameter:
`hide: ${ 'part' if vlen == 1 else 'none' }`
Unsure what it does, but the blocks cannot be used unless this line is removed.

I think the code is failing to link in my installation of GR 3.8.1.0 (Python 3.7.7), I'm getting this error:
`AttributeError: type object 'specest' has no attribute 'welch'`
but have no idea how to debug this...

...Does anyone use this module anymore, or is there something newer that I don't know about?

**Comment by sodaBitters** [comment]
similar issue on the GR master branch here:
https://github.com/gnuradio/gnuradio/pull/3130/files

**Comment by mbr0wn** [comment]
I actually have a whole bunch of fixes not checked in (including this) from last GRCon. Need to test, will then push.

**Comment by mbr0wn** [comment]
OK that should have fixed this.

**Comment by sodaBitters** [comment]
works beautifully - thanks Martin!
